## 라이브러리 불러오기
- 라이브러리 불러오고, 버전 확인

In [2]:
import numpy as np 
print(np.__version__)

# import numpy
# print(numpy.__version__)

1.21.6


## NumPy 배열로 변환
- 수치 연산을 하고 싶다!
- 파이썬 기초 자료형을 배열로 변환한다!
--> 형변환 이 개념과 유사

In [12]:
temp = [1, 2, 3, 4, 5, 6, 7, 8]
result = np.array(temp)
print(type(result))
print(result)

<class 'numpy.ndarray'>
[1 2 3 4 5 6 7 8]


- 배열의 크기
- 배열은 1차원 / 2차원 / 3차원

In [13]:
result.shape

(8,)

In [14]:
result.ndim

1

- 다차원 배열 만들기

In [17]:
temp = np.array([[2, 4, 6], [8, 10, 12]])
print(temp)
print(temp.shape)
print(temp.ndim)

[[ 2  4  6]
 [ 8 10 12]]
(2, 3)
2


- 3차원 배열도 가능
- 4차원 가능.... 

## 여러 배열 생성 기본 함수
- np.arange()

In [18]:
temp = np.arange(5)
temp

array([0, 1, 2, 3, 4])

In [26]:
temp_z = np.zeros((2, 2, 2))
print(temp_z)
print(temp_z.shape)
print(temp_z.ndim)

# 데이터 타입
print(temp_z.dtype)

[[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]]
(2, 2, 2)
3
float64


- 데이터 타입 크기 지정

In [35]:
temp_one = np.ones((255, 255), dtype='int32')
print(temp_one)
print(temp_one.dtype)

[[1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 ...
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]]
int32


In [40]:
result = temp_one.reshape(5, -1, 5)
print(result)
print(result.shape)

[[[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  ...
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  ...
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  ...
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  ...
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  ...
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]]
(5, 2601, 5)


## 인덱싱 슬라이싱

In [41]:
temp = np.arange(0, 4)
print(temp)


[0 1 2 3]


In [43]:
temp[0:2]

array([0, 1])

In [44]:
temp = np.arange(3, 30, 3).reshape(3, 3)
temp

array([[ 3,  6,  9],
       [12, 15, 18],
       [21, 24, 27]])

In [46]:
temp[0:2, 0:2]

array([[ 3,  6],
       [12, 15]])

In [47]:
temp[1:3, :]

array([[12, 15, 18],
       [21, 24, 27]])

In [48]:
temp[:, 1:3]

array([[ 6,  9],
       [15, 18],
       [24, 27]])

## 난수 생성
- 임의의 숫자 생성

In [50]:
# from numpy import random
# x = random.rand()

import numpy
x = numpy.random.rand()

print(x)

0.08706227270644129


- 임의의 정수

In [55]:
from numpy import random 
x = random.randint(1000, size = (5, 2, 3))
print(x)

[[[884 611 400]
  [389 232  29]]

 [[742 808 169]
  [515 251 316]]

 [[710 171 468]
  [505 863 616]]

 [[662 328 311]
  [492 500 666]]

 [[704 368  24]
  [674 294 640]]]


In [60]:
x = random.rand(2, 6)
print(x)

[[0.51750101 0.94497415 0.68981745 0.81964736 0.23216838 0.03077026]
 [0.64339062 0.88203458 0.43330056 0.51517256 0.52331727 0.2964188 ]]


## 배열 연산

In [68]:
array01 = random.randint(100, size = (5, 2))
array02 = random.randint(1000, size = (5, 2))

print(array01)
print(array02)

[[40 25]
 [55 11]
 [13 33]
 [25 45]
 [97 53]]
[[499 188]
 [110 336]
 [975 373]
 [942  21]
 [980 290]]


In [69]:
import numpy as np 

# 덧셈
np.add(array01, array02)

array([[ 539,  213],
       [ 165,  347],
       [ 988,  406],
       [ 967,   66],
       [1077,  343]])

In [70]:
# 뺄셈
np.subtract(array01, array02)

array([[-459, -163],
       [ -55, -325],
       [-962, -340],
       [-917,   24],
       [-883, -237]])

In [71]:
# 곱셈
np.multiply(array01, array02)

array([[19960,  4700],
       [ 6050,  3696],
       [12675, 12309],
       [23550,   945],
       [95060, 15370]])

In [72]:
# 나눗셈
np.divide(array01, array02)

array([[0.08016032, 0.13297872],
       [0.5       , 0.0327381 ],
       [0.01333333, 0.08847185],
       [0.02653928, 2.14285714],
       [0.09897959, 0.18275862]])

## 소숫점 제거

In [73]:
array01 = np.trunc([-1.23, 1.23])
array01

array([-1.,  1.])

In [75]:
array01 = np.round([-1.235231312, 1.231231231], 3)
array01

array([-1.235,  1.231])

In [76]:
array01 = np.floor([-1.235231312, 1.231231231])
array01

array([-2.,  1.])

In [77]:
array01 = np.ceil([-1.235231312, 1.231231231])
array01

array([-1.,  2.])

## NumPy 조건식
- numpy.select() : 다중조건문
- numpy.where() : 단일조건문

In [78]:
array01 = np.arange(10)
array01

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [79]:
# 배열에서 5 미만이면, 원래 값 반환, 그 외에는 원래 값 * 100
import numpy as np 

#        조건식         참       거짓
np.where(array01 < 5, array01, array01 * 100)

array([  0,   1,   2,   3,   4, 500, 600, 700, 800, 900])

- 다중조건문


In [80]:
# 배열에서 3 미만이면, 원래 값 + 10, 7 이상이면 * 100, 그 외에는 원래 값
cond_list =   [array01 < 3,  array01 >= 7]
result_list = [array01 + 10, array01 * 100]

np.select(cond_list, result_list, default = array01)

array([ 10,  11,  12,   3,   4,   5,   6, 700, 800, 900])